export const featuredCars = [
  {
    id: 1,
    make: "Toyota",
    model: "Camry Hybrid XSE",
    year: 2024,
    price: 32999,
    images: ["https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?q=80&w=1200&auto=format&fit=crop"],
    transmission: "Automatic",
    fuelType: "Hybrid",
    bodyType: "Sedan",
    mileage: 4200,
    color: "Pearl White",
    wishlisted: false,
    featured: true,
    status: "AVAILABLE",
    description: "2024 Toyota Camry Hybrid XSE featuring sport-tuned suspension, dual-tone panoramic roof, and dynamic radar cruise control.",
  },
  {
    id: 2,
    make: "Honda",
    model: "Civic Type R",
    year: 2024,
    price: 44799,
    images: ["https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?q=80&w=1200&auto=format&fit=crop"],
    transmission: "Manual",
    fuelType: "Gasoline",
    bodyType: "Hatchback",
    mileage: 1800,
    color: "Sonic Gray",
    wishlisted: true,
    featured: true,
    status: "AVAILABLE",
    description: "Pure track capability with everyday usability. Turbocharged 2.0-liter VTEC engine paired with a crisp 6-speed manual gearbox.",
  },
  {
    id: 3,
    make: "Tesla",
    model: "Model 3 Performance",
    year: 2024,
    price: 52990,
    images: ["https://images.unsplash.com/photo-1560958089-b8a1929cea89?q=80&w=1200&auto=format&fit=crop"],
    transmission: "Automatic",
    fuelType: "Electric",
    bodyType: "Sedan",
    mileage: 3100,
    color: "Deep Blue",
    wishlisted: false,
    featured: true,
    status: "AVAILABLE",
    description: "0-60 mph in 2.9 seconds. Dual Motor All-Wheel Drive, adaptive damping suspension, and Full Self-Driving hardware 4.0 capability.",
  },
  {
    id: 4,
    make: "BMW",
    model: "M4 Competition Coupe",
    year: 2024,
    price: 86500,
    images: ["https://images.unsplash.com/photo-1555215695-3004980ad54e?q=80&w=1200&auto=format&fit=crop"],
    transmission: "Automatic",
    fuelType: "Gasoline",
    bodyType: "Sedan",
    mileage: 2400,
    color: "Isle of Man Green",
    wishlisted: false,
    featured: true,
    status: "AVAILABLE",
    description: "503-hp twin-turbo inline 6-cylinder engine. Carbon fiber bucket seats, M xDrive AWD, and precision racetrack handling.",
  },
  {
    id: 5,
    make: "Ford",
    model: "Mustang Mach-E GT",
    year: 2024,
    price: 59990,
    images: ["https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?q=80&w=1200&auto=format&fit=crop"],
    transmission: "Automatic",
    fuelType: "Electric",
    bodyType: "SUV",
    mileage: 5100,
    color: "Cyber Orange",
    wishlisted: false,
    featured: true,
    status: "AVAILABLE",
    description: "All-electric performance SUV with MagneRide active damping system, Brembo performance brakes, and 480 instant horsepower.",
  },
  {
    id: 6,
    make: "Hyundai",
    model: "IONIQ 5 N",
    year: 2024,
    price: 66100,
    images: ["https://images.unsplash.com/photo-1617814076367-b759c7d7e738?q=80&w=1200&auto=format&fit=crop"],
    transmission: "Automatic",
    fuelType: "Electric",
    bodyType: "SUV",
    mileage: 1200,
    color: "Performance Blue",
    wishlisted: false,
    featured: true,
    status: "AVAILABLE",
    description: "High-performance EV crowned with N e-shift paddle gear simulation, corner-carving differential, and 641 horsepower boost mode.",
  },
  {
    id: 7,
    make: "Tata",
    model: "Harrier Dark Edition",
    year: 2024,
    price: 26900,
    images: ["https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?q=80&w=1200&auto=format&fit=crop"],
    transmission: "Automatic",
    fuelType: "Diesel",
    bodyType: "SUV",
    mileage: 6800,
    color: "Oberon Black",
    wishlisted: false,
    featured: true,
    status: "AVAILABLE",
    description: "Bold road presence with Land Rover D8-derived OMEGA Architecture, Level 2 ADAS active safety suite, and luxurious ventilated seats.",
  },
  {
    id: 8,
    make: "Mahindra",
    model: "XUV700 AX7 Luxury",
    year: 2024,
    price: 29500,
    images: ["https://images.unsplash.com/photo-1549399542-7e3f8b79c341?q=80&w=1200&auto=format&fit=crop"],
    transmission: "Automatic",
    fuelType: "Gasoline",
    bodyType: "SUV",
    mileage: 8400,
    color: "Midnight Black",
    wishlisted: false,
    featured: true,
    status: "AVAILABLE",
    description: "Flagship 7-seater SUV with panoramic Skyroof, Sony 3D Immersive audio with 12 speakers, and mStallion Turbo engine.",
  },
  {
    id: 9,
    make: "BMW",
    model: "Z4 M40i Roadster",
    year: 2023,
    price: 67800,
    images: ["https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=1200&auto=format&fit=crop"],
    transmission: "Automatic",
    fuelType: "Gasoline",
    bodyType: "Convertible",
    mileage: 7200,
    color: "Frozen Grey",
    wishlisted: false,
    featured: true,
    status: "AVAILABLE",
    description: "Open-top sports roadster with near-perfect 50:50 weight distribution, M Sport differential, and intoxicating 382 hp turbo engine.",
  },
];

export const carMakes = [
  { id: 1, name: "BMW", image: "/make/bmw.webp" },
  { id: 2, name: "Tesla", image: "/make/bmw.webp" },
  { id: 3, name: "Toyota", image: "/make/ford.webp" },
  { id: 4, name: "Honda", image: "/make/honda.webp" },
  { id: 5, name: "Hyundai", image: "/make/hyundai.webp" },
  { id: 6, name: "Tata", image: "/make/tata.webp" },
  { id: 7, name: "Mahindra", image: "/make/mahindra.webp" },
  { id: 8, name: "Ford", image: "/make/ford.webp" },
];

export const bodyTypes = [
  { id: 1, name: "SUV", image: "/body/suv.webp" },
  { id: 2, name: "Sedan", image: "/body/sedan.webp" },
  { id: 3, name: "Hatchback", image: "/body/hatchback.webp" },
  { id: 4, name: "Convertible", image: "/body/convertible.webp" },
];

export const faqItems = [
  {
    question: "How does the test drive booking work?",
    answer:
      "Simply find a vehicle you're interested in, click 'Inspect Vehicle & Book Drive', and choose your preferred available calendar slot. Our system confirms your reservation instantly.",
  },
  {
    question: "Can I search for cars using an image or car photo?",
    answer:
      "Yes! Our Google Gemini Vision 2.0 AI Lens allows you to drag and drop or snap any car photo. The neural network automatically recognizes make, body class, and color to filter inventory.",
  },
  {
    question: "Are all vehicles certified and inspected?",
    answer:
      "Every vehicle in our catalog undergoes rigorous 150-point diagnostic inspections with clean title guarantees and comprehensive service histories.",
  },
  {
    question: "What should I bring to my test drive appointment?",
    answer:
      "Please bring a valid driver's license and proof of insurance. Our concierge will have the vehicle sanitized, charged or fueled, and ready for your arrival.",
  },
];
